### ISSUE TITLE
Rendering video frame

### ISSUE THREAD

**Issue by kalwalt** [augmentmy-world/arStudio#27]
@itamayo We continue the discussion started from this comment https://github.com/augmentmy-world/arStudio/issues/23#issuecomment-597725175 Can you elaborate a bit more if you can and when you have time, maybe referencing to the code? Thank you! :slightly_smiling_face:

**Comment by itamayo** [comment]
Basically it is about encompassing everything in the same canvas (video and webgl). For this, a 3d plane can be created as a texture for the video and it is inserted in the 3d world. Example for 3d plane and video (I have done without threejs).
https://threejs.org/examples/#webgl_materials_video
To improve jsartoolkit processing it be useful use this technique since it can adjust FPS of processing data.
Soon as I have enough time , I would like to implemented this approach in this project as a branch show we can test it.

**Comment by kalwalt** [comment]
Thank you @itamayo interesting approach, if you need some help or support for jsartoolkit5 and arStudio just ask, you are welcome! :smile:

**Comment by itamayo** [comment]
I've been working a bit, it will take me longer than I expected since I'm trying to understand how is built "litegl" to do it. At least, I already have video rendering on the plane, let's see how it goes ...

**Comment by kalwalt** [comment]
@itamayo **arStudio** is built on top of [litescene.js](https://github.com/jagenjo/litescene.js) but some part of the code use [litegl.js](https://github.com/jagenjo/litegl.js) as you said, maybe Three.js  is easier but i think you can do the same things with litescene.js. If you need help just ping me or @ThorstenBux .

**Comment by itamayo** [comment]
I have some problem with the shader but It works. Graphs is not my background, any help @kalwalt ? 
![Screenshot from 2020-03-17 14-34-16](https://user-images.githubusercontent.com/3738104/76861351-bf100700-685c-11ea-9183-aad657040d33.png)

I did a pull request for new branch ...

**Comment by kalwalt** [comment]
Wow! @itamayo That is awesome! what do you mean for `Graphs is not my background,`? 
I will review and test your PR.

**Comment by itamayo** [comment]
i mean that I am not expert of graphics manipulation =)

**Comment by kalwalt** [comment]
> I mean that I am not expert of graphics manipulation =)

Don't worry the important thing is the solution!

**Comment by ThorstenBux** [comment]
Fixed with https://github.com/augmentmy-world/arStudio/pull/28
